ass2: LinkedList.o ShoppingCart.o ItemToPurchase.o main.o

	g++ ShoppingCart.o LinkedList.o ItemToPurchase.o main.o -o ass2


ShoppingCart.o: ShoppingCart.cpp

	g++ -c -std=c++11 ShoppingCart.cpp

LinkedList.o: LinkedList.cpp

	g++ -c -std=c++11 LinkedList.cpp

ItemToPurchase.o: ItemToPurchase.cpp
	
	g++ -c -std=c++11 ItemToPurchase.cpp

main.o: main.cpp
	
	g++ -c -std=c++11 main.cpp

